version: '3.1'

# https://hub.docker.com/_/zookeeper
# https://www.elkozmon.com/zoonavigator/basics/usage/

services:
  zoonavigator:
    image: elkozmon/zoonavigator:1.0.1
    restart: always
    hostname: zoonavigator
    ports:
     - 8090:8090
    environment:
      CONNECTION_ZOO_CONN: zookeeper_1:2181
      AUTO_CONNECT_CONNECTION_ID: ZOO
      HTTP_PORT: 8090

  zookeeper_1:
    image: zookeeper
    restart: always
    hostname: zookeeper_1
    ports:
      - 2181:2181
    volumes:
      - ./conf/:/conf/
    environment:
      ZOO_MY_ID: 1