version: '3.1'

# https://hub.docker.com/_/zookeeper
# https://www.elkozmon.com/zoonavigator/basics/usage/

services:
  web:
    image: elkozmon/zoonavigator-web:0.6.1
    hostname: zoonavigator-web
    ports:
     - 8000:8000
    environment:
      AUTO_CONNECT_CONNECTION_STRING: zookeeper_1:2181
      WEB_HTTP_PORT: 8000
      API_HOST: "api"
      API_PORT: 9000
    depends_on:
     - api
    restart: always

  api:
    image: elkozmon/zoonavigator-api:0.6.1
    hostname: zoonavigator-api
    environment:
      API_HTTP_PORT: 9000
    restart: always

  zookeeper_1:
    image: zookeeper
    restart: always
    hostname: zookeeper_1
    ports:
      - 2181:2181
    volumes:
      - ./conf/:/conf/
    environment:
      ZOO_MY_ID: 1